name: Karate Tests

on:
  workflow_dispatch:  # This line enables manual triggering of the workflow
    inputs:
      environment:
        description: 'The environment to use'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Dependencies
      run: mvn install -DskipTests=true

    - name: Set up .env file
      run: |
        echo "API_URL=${{ secrets.API_URL }}" >> .env
        echo "DEV_USERNAME=${{ secrets.DEV_USERNAME }}" >> .env
        echo "DEV_USEREMAIL=${{ secrets.DEV_USEREMAIL }}" >> .env
        echo "DEV_USERPASSWORD=${{ secrets.DEV_USERPASSWORD }}" >> .env
        echo "QA_USERNAME=${{ secrets.QA_USERNAME }}" >> .env
        echo "QA_USEREMAIL=${{ secrets.QA_USEREMAIL }}" >> .env
        echo "QA_USERPASSWORD=${{ secrets.QA_USERPASSWORD }}" >> .env

    - name: Run Karate Tests
      run: mvn test -Dkarate.options="--tags @smoke" -Dkarate.env="${{ github.event.inputs.environment }}"

    - name: Publish Karate Test Results
      uses: actions/upload-artifact@v3
      with:
        name: karate-test-results
        path: target/karate-reports/
