name: Karate Mock Server Tests

on:
  workflow_dispatch:  # This line enables manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Dependencies
      run: mvn install -DskipTests=true

    - name: Set up .env file
      run: |
        echo "API_URL=${{ secrets.API_URL }}" >> .env
        echo "DEV_USERNAME=${{ secrets.DEV_USERNAME }}" >> .env
        echo "DEV_USEREMAIL=${{ secrets.DEV_USEREMAIL }}" >> .env
        echo "DEV_USERPASSWORD=${{ secrets.DEV_USERPASSWORD }}" >> .env
        echo "QA_USERNAME=${{ secrets.QA_USERNAME }}" >> .env
        echo "QA_USEREMAIL=${{ secrets.QA_USEREMAIL }}" >> .env
        echo "QA_USERPASSWORD=${{ secrets.QA_USERPASSWORD }}" >> .env
    
    - name: Start Mock Server
      run: |
        echo "Starting mock server..."
        mvn test-compile exec:java -Dexec.mainClass=conduitApp.SimpleMockRunner -Dexec.classpathScope=test &
        echo $! > mock_server_pid.txt

    - name: Wait for Mock Server to Start
      run: |
        for i in {1..5}; do
          if nc -zv localhost 8088; then
            echo "Mock server is up and running!"
            exit 0
          fi
          echo "Waiting for mock server..."
          sleep 3
        done
        echo "Mock server failed to start."
        cat mock_server.log
        exit 1

    - name: Run Karate Tests
      run: mvn test -Dkarate.options="--tags @mock"

    - name: Publish Karate Test Results
      uses: actions/upload-artifact@v3
      with:
        name: karate-test-results
        path: target/karate-reports/
